#spring:
#  profiles:
#    active: dev

---
spring:
  profiles: dev

  cloud:
    consul:
      enabled: true
      host: 192.168.1.223
      port: 8500
      discovery:
        enabled: true
        instanceId: checkouts0
        serviceName: checkouts
        #hostname: 192.168.0.6
        #port: ${server.port}
        #healthCheckUrl: http://192.168.0.6:8089/health
        healthCheckInterval: 10s
        tags: dev
    stream:
      bindings:
        output_custom_evt:
          destination: SpringCloudStream
          binder: rabbit0

      binders:
        rabbit0:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.223
                port: 5672
                username: dev
                password: devUser*1
                virtual-host: /

turbine:
  appConfig: checkouts
  aggregator:
    clusterConfig: test
  clusterNameExpression: metadata['cluster']

logging:
  level:
    com:
      cxy:
        apis: DEBUG

---
spring:
  profiles: qa

---
spring:
  profiles: product

---

