spring:
  application:
    name: com.cxy.charge.checkoutsApp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

  cloud:
    consul:
      enabled: true
      host: 192.168.1.223
      port: 8500
      discovery:
        enabled: true
        instanceId: checkouts0
        serviceName: checkouts
        hostname: 192.168.0.6
        port: ${server.port}
        healthCheckUrl: http://192.168.0.6:8089/health
        healthCheckInterval: 10s
        tags: ${spring.profiles.active}
    stream:
      bindings:
        output_custom_evt:
          destination: SpringCloudStream
          binder: rabbit0

      binders:
        rabbit0:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.223
                port: 5672
                username: dev
                password: devUser*1
                virtual-host: /

  profiles:
    active: dev
---
spring:
  profiles: dev

server:
  address: 0.0.0.0
  port: 8089

turbine:
  appConfig: checkouts
  aggregator:
    clusterConfig: test
  clusterNameExpression: metadata['cluster']

logging:
  level:
    com:
      cxy:
        apis: DEBUG
---
spring:
  profiles: test

server:
  address: 0.0.0.0
  port: 8080

---
spring:
  profiles: prod

server:
  address: 0.0.0.0
  port: 8080

---

